# Generated by Django 6.0.5 on 2026-05-31 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_clicktrack_user_customuser_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricealert',
            name='alert_type',
            field=models.CharField(choices=[('ANY', 'Any Change'), ('TARGET', 'Target Price')], default='ANY', max_length=50),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='current_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='target_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
